# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HowlFirebaseLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HowlFirebaseLogin

# add the Firebase pod for Google Analytics

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Database'

pod 'GoogleSignIn'

# Facebook
pod 'FBSDKCoreKit'  
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBSDKPlacesKit'


end
